atom/vim-mode

- lib/status-bar-manager.coffee
- lib/vim-mode.coffee
- package.json
- spec/vim-mode-spec.coffee
:warning: Depends on https://github.com/atom/status-bar/pull/51 being merged and released in Atom v0.178 :warning:
Signed-off-by: Max Brunsfeld <maxbrunsfeld@gmail.com>
> Use status-bar through new service API

- lib/motions/find-motion.coffee
- spec/motions-spec.coffee
There was a bug that repeated f/t motion wouldn't get canceled if we tried to move too many times.
E.g. in the test string 'abcabcabcabc' with cursor at the start, the motion 11fa would actually jump to the second a; the old test didn't uncover it because, as it happened, 10fa jumped to the first 'a', so the cursor didn't move. It was because indexOf with a negative fromIndex simply searched the whole string again.
Then while testing the backward motion F/T, I found that if it so happens that the character we're looking for is at the beginning of the line, the motion would simply go there, and again wouldn't be canceled. That's because in lastIndexOf, a negative fromIndex is treated as 0 and the first character gets searched (where it shouldn't).
So here I fix both cases. Feel free to …
> Fix repeated find motion

- lib/motions/general-motions.coffee
- spec/motions-spec.coffee
shift-B would currently only look for spaces and newlines; it needs to handle any whitespace in skipping to the previous word
AllWhitespace modeled after lib/text-objects.coffee
This is my first little contribution to Atom, feel free to let me know if I'm doing something wrong.
> :bug: fix tab handling in shift-B

- docs/overview.md
- lib/motions/general-motions.coffee
- lib/vim-mode.coffee
- spec/motions-spec.coffee
Hi, 
VIM has the `whichwrap` setting that allows wrapping some operations across line boundaries. I have now added wrapping of left and right motion (VIM values h,l,<,>) for myself because I use it heavily; I'm submitting it here for your consideration.
I know that this particular setting for `h` and `l` is "not recommended" in VIM, but the reasons for it that I could find are to do with plugins expecting the non-wrapping behavior – does anybody here know of actual problems with wrapping `h`,`l`, especially if they would translate to vim-mode in Atom?
Note that the VIM whichwrap settings `b`, `[` and `]` are already the standard behaviour in Atom vim-mode. The remaining settings `s` and `~` I don't really care about.
> feature: VIM whichwrap

- lib/motions/general-motions.coffee
- lib/motions/search-motion.coffee
- lib/operators/general-operators.coffee
- lib/operators/input.coffee
- lib/operators/put-operator.coffee
- lib/settings.coffee
- lib/vim-mode.coffee
- lib/vim-state.coffee
- spec/operators-spec.coffee
I find it much nicer to have the default register mapped to the clipboard for better interop with the standard editor world, so this PR adds a new option to enable that behaviour.
It also moves the settings into their own module to serve a single point for defining options and any associated lookup functions.
Related:  #308
> Adds useClipboardAsDefaultRegister option.

- keymaps/vim-mode.cson
Maps i_CTRL-U to `editor:delete-to-beginning-of-line`
I will write a test for this tomorrow. :smile:
> Adds keymap for insert mode CTRL-U

- lib/vim-mode.coffee
- package.json
In response to #536.
This exposes `getState(editor)` along with `getGlobalState()` via a versioned `vim-mode` service. The consumer then has direct access to the editor's VimState instance. Therefore I made the service version equal to vim-mode's package version.
This will allow packages extending vim-mode to have access to its core state (such as registers, marks...) but also `pushOperations`, which offers a wealth of possibilities.
It may be advisable ultimately to box the VimState instance into a service proxy object, so as to expose a restricted and stable API, isolated from what amounts to the core of vim-mode. This may be too early though, as we may be too restrictive early on. I don't know what your versioning policy is, but this may be a worthy goal for vim-mode 1.0.
> Publish vim-mode as an atom service

- lib/motions/find-motion.coffee
- spec/motions-spec.coffee
Hi,
VIM has the 'cpoptions' option that directs where VIM should behave like VI; one of the flags is ';':
```
;	When using |,| or |;| to repeat the last |t| search
and the cursor is right in front of the searched
character, the cursor won't move. When not included,
the cursor would skip over it and jump to the
following occurrence.
```
This PR implements VIM default behavior where ';' after 't' **does move**.
I haven't realized until today that I've been used to VIM behaviour, as opposed to what VI would do. How about others? Which way would be better in atom/vim-mode?
> till motion should be repeatable with ; (VIM default)

- keymaps/vim-mode.cson
- lib/vim-state.coffee
- spec/text-objects-spec.coffee
I just :+1: #418 and thought I'd give a go at actually implementing it.
Hopefully code is straight forward.
It's not exactly like vim right now, if you're not inside a tag it won't do anything, vim is smart enough to move to the next tag and then do the action. However that seems to be how the other motions in atom are done right now anyway...
> Add 'i t' for inside tags

- lib/motions/general-motions.coffee
- spec/operators-spec.coffee
This fixes #543
For some reason having yanked the whole line before the delete + motion made the wasReversed variable be true (it was false without the yank)
> :bug: fix 'd' and 'c' sometimes deleting a char before cursor

- package.json
Start using the new Service API versioning for `status-bar`. cc @maxbrunsfeld 
**Don't merge until Atom 0.187**
> Use new status-bar API versioning 

- lib/vim-state.coffee
If I understand it correctly, this patch should be appropriate. If not, at least I'll improve my understanding. 8-)
> vim-mode should dispose all its subscriptions

- lib/operators/input.coffee
- lib/vim-state.coffee
- spec/operators-spec.coffee
An `I` or `A` insert operation should be repeated as such, rather than
as a simple `i` or `a` operation.
Fixing this led me to find a bug: repeated insert didn’t position the
cursor correctly at the last inserted character (not after it), so even
repeated `a` or `i` wouldn’t work right; this is fixed too.
Fixes #538 .
> :fix: repeating insert operations

- docs/operators.md
- keymaps/vim-mode.cson
- lib/operators/general-operators.coffee
- lib/vim-state.coffee
- spec/operators-spec.coffee
The code is adapted from `~` for toggle case. 
I know there is `cmd-K cmd-U` to uppercase in Atom, but it doesn't end the visual mode as VIM would.
> :feature: `U` and `u` for upper-casing and lower-casing

- lib/motions/search-motion.coffee
- spec/motions-spec.coffee
previously, `*` between two words could select the preceding, not the
following word; and `#` would routinely first find the current word and
then go find the previous occurrence; this patch fixes both issues
> :fix: `*` and `#` motion

- lib/status-bar-manager.coffee
- lib/vim-state.coffee
This is a suggestion that we may want to show the submode in the status bar; the PR already includes values for replace mode, proposed in #573.
> :feature: show submode in status bar

- lib/view-models/search-view-model.coffee
- lib/view-models/vim-command-mode-input-view.coffee
- spec/motions-spec.coffee
- spec/operators-spec.coffee
- spec/text-objects-spec.coffee
- spec/vim-state-spec.coffee
fixes a bug where you're unable to see the text you're typing when hitting `/` to search
searching is working on this PR, but I introduced a regression into Motion.Till where the search input box shows up whereas previously it was invisible
cc @maxbrunsfeld
> Use TextEditorElement for VimCommandModeInputView

- lib/view-models/vim-command-mode-input-view.coffee
Since pr #582 commands with `:not([mini])` filter in command definition get fired in search-mode editor in case of a missing `mini` attribute in the `atom-text-editor` element.
The way how the editor-view was created in the bottom panel has changed from:
```javascript
new TextEditorView(mini: true)
```
to:
```javascript
@editorElement = document.createElement "atom-text-editor"
@editorElement.classList.add('editor')
@editorElement.getModel().setMini(true)
```
The `setMini` setter only sets the mini attribute in the model not in the editor-view.
> Fix: Prevent ":not([mini])" commands from being fired in search-mode

- lib/global-vim-state.coffee
- lib/motions/index.coffee
- lib/motions/search-motion.coffee
- lib/view-models/search-view-model.coffee
- lib/vim-state.coffee
- spec/motions-spec.coffee
Make current search part of the global state.
Also prevents `%` from affecting `n`; and also puts the word searched for by `*` and `#` into search history.
Obsoletes #606. Fixes #190 I think.
> Global current search

- docs/motions.md
- lib/motions/search-motion.coffee
- lib/view-models/search-view-model.coffee
- spec/motions-spec.coffee
fixes #578 
Now search can be repeated with `/<enter>`, `//<enter>`, `?<enter>` and `??<enter>`.
Beyond that, I think I'm beginning to agree that / should be handled by ex-mode (#596).
> Repeating search with //, ?? et al.

- lib/operators/general-operators.coffee
- spec/motions-spec.coffee
- spec/operators-spec.coffee
when a motion fails or selects 0 characters, yank/delete/etc operators currently put “” in the appropriate register, but they shouldn’t do that
> register should never be replaced by an empty string

- lib/operators/general-operators.coffee
- lib/operators/input.coffee
- spec/operators-spec.coffee
With multiple cursors, if a motion selects nothing and other motions select something, delete operations would correctly delete the selections, but the empty selections would delete a character, which is unexpected. 
For example, with two cursors, `dtx` should delete until 'x' only on the line that has an 'x' - of only one does, the other line would delete a character; if neither line has x, nothing would be deleted. 
Another example: `d0` with two cursors, one at the beginning of the first line and another on the second line but not its beginning, should not delete the first character of the line.
> Fix delete with empty selections

- lib/motions/general-motions.coffee
- lib/operators/general-operators.coffee
- lib/vim-state.coffee
- spec/operators-spec.coffee
`x` should only wrap to next line with `vim-mode.wrapLeftRightMotion = true`, and only with a count or on an empty line.
The PR also adds a bit to the tests for X.
> fix wrapping behavior of x

- spec/operators-spec.coffee
`gU$` and such could put the cursor at the end of the line, not the last character as expected in vim mode
> fix cursor position after operator

- lib/vim-state.coffee
- spec/prefixes-spec.coffee
with `apm test -1` I've uncovered another use of a deprecated method, this fixes it.
How does one add `-1` to `apm test` in Travis tests?
> fix deprecation of editor.getUri

- lib/operators/general-operators.coffee
- spec/motions-spec.coffee
- spec/operators-spec.coffee
Default Vim behavior is to move to the first nonblank character in the line.
Also, here seems to be a plugin that causes Vim to leave the cursor in the
same column if possible.  vim-mode's old behavior did neither.
This PR makes vim-mode work just like stock vim.
> make dd leave cursor on nonblank char

- lib/vim-state.coffee
- spec/vim-state-spec.coffee
Before this change, `deactivateVisualMode()` unnecessarily move cursor Left when selection is Reversed.
* `v` to enter visual-mode
* `kk`, `esc` move Cursor one column **Left** position to expected position.
This PR fix above bug.
All test pass, I don't think additional test required for this fix.
> don't moveLeft() if selection.isReversed()

- lib/operators/input.coffee
- spec/operators-spec.coffee
This fixes the problem where bracket-matcher's autocompletion of quotes or brackets would confuse replay of inserts. This is mentioned in #392, #650, and related to #564.
> Fix insert redo

- lib/vim-state.coffee
The error was caused by event handlers of `failed-to-compose` cancelling the operation that’s already being cancelled.
Replicate the issue by pressing `cm`.
May be what caused #713, #646, #642 - and certainly is the one described in #633.
> fix Uncaught NotFoundError

- lib/operators/general-operators.coffee
- spec/operators-spec.coffee
Delete operations with multiple cursors are undone one by one. They should be undone all together.
> Multiple cursor undo of delete operations

- lib/operators/general-operators.coffee
- lib/operators/input.coffee
- lib/operators/put-operator.coffee
- lib/operators/replace-operator.coffee
We never do use those parameters. Adapting #581 to not use selectOptions is quite simple.
> clean up: remove unused selectOptions and allowEOL

- docs/operators.md
- spec/motions-spec.coffee
- spec/vim-state-spec.coffee
All style, very little substance.
> fix some more command->normal mode renames

- docs/overview.md
- keymaps/vim-mode.cson
- lib/operators/input.coffee
- lib/vim-state.coffee
- spec/operators-spec.coffee
- spec/vim-state-spec.coffee
- styles/vim-mode.less
This addresses #562; also it partly addresses #564.
I got the inspiration for this implementation from @brunetton's `atom-overtype-mode` package.
*(edited)*
**Features:**
* `backspace` acts as undo
* block cursor and status bar indication of replace mode
**Limitations:**
* `.` with multiple cursors may eat a character for one of those cursors, but I’ve no idea why
> add replace mode

- lib/motions/find-motion.coffee
- spec/motions-spec.coffee
Till is an exceptional movement in that when selecting, it selects the current character even though it doesn't move the cursor. This was failing the normal selection machinery that expects cursor movements.
Fixes #618.
> Fix Till when selecting

- lib/operators/put-operator.coffee
- spec/operators-spec.coffee
If you have a word in the clipboard and `p` it at the end of the line, the cursor ends up on the second-to-last character of the word, not on the last one, as expected. This PR fixes that.
> Fix p cursor position

- lib/motions/search-motion.coffee
- spec/motions-spec.coffee
When Atom starts, there is no search history, and `n` would advance by a character because it searches for nothing, which matches everywhere.
This PR fixes that.
> repeating without search history should do nothing

- lib/prefixes.coffee
This PR addresses the issue that generated an exception in #760 and #741. It doesn't add counts to text objects, that can be another PR; but at least vim-mode doesn't crash anymore on `c3aw`.
We might close #760 and #741 and open an issue that text objects don't have counts.
> fix: isLinewise shouldn't be required

- keymaps/vim-mode.cson
This updates vim-mode to match Vim's binding.
I assume this was a simple typo?  https://github.com/atom/vim-mode/commit/c35d2d6744c3beaa91f8bc9e82ee19f11680478b
> Make control-t return from symbol, not control-shift-t

- lib/operators/input.coffee
- lib/vim-state.coffee
Removes some code duplication.  Counts still work of course.
There might be some other places we can do this but not sure if there's interest there is in this sort of cleanup.
> implement substitute using the change operator

- docs/overview.md
- keymaps/vim-mode.cson
- lib/insert-mode.coffee
- lib/vim-state.coffee
- spec/insert-mode-spec.coffee
This PR implements VIM insert-mode commands `ctrl-y` and `ctrl-e` for copying from the line above/below the cursor.
A few questions in relation to this PR:
* is `lib/insert-mode.coffee` an OK new file for this? 
* if so, should #720 live there, too?
* should I worry that some might use `ctrl-e` for going to the end of the line? (default in Atom)
Oh, and congratulations on Atom 1.0.0! :fireworks: :balloon:
> feature: copy character from line above/below

- lib/global-vim-state.coffee
- lib/motions/find-motion.coffee
- lib/vim-state.coffee
- spec/motions-spec.coffee
- spec/spec-helper.coffee
Makes find state global, like search state (history) is shared across text editors.
An example: if you do `t*` to move the cursor to the next `*` in one editor, switch to another editor, and do `;`, you'll go to the next `*` as well.
> make find state global

- lib/motions/general-motions.coffee
- lib/vim-state.coffee
- spec/motions-spec.coffee
- spec/scroll-spec.coffee
- spec/vim-state-spec.coffee
Currently, motions would individually ensure that cursor doesn't end up after the last character of a line. This fails in a number of circumstances, e.g. with mouse clicks to move/add a cursor, and with specs that `setCursorBufferPosition` to put the cursor where it should never be.
This PR reacts to any cursor movement with TextEditor's `onDidChangeCursorPosition` and any cursor addition with `onDidAddCursor` and makes sure the cursor never goes where it doesn't belong.
The PR also fixes some tests that expected the cursor after the last character in command mode, and removes some outdated spec comments.
> use onDidChangeCursorPosition for keeping cursor in line

- lib/motions/general-motions.coffee
- spec/vim-state-spec.coffee
Left and right motion across the beginning of a selection behaves inconsistently.
On a line with the text `abcde` and cursor on the `c`:
1. press `v` to enter visual mode, `c` is selected;
2. press `l`, `cd` is selected;
3. press `h`, `c` is selected;
4. press `h`, `bc` is selected;
5. press `l`, `c` is selected;
6. press `l`, `c` is *still* selected but it should be `cd` now.
7. press `l` and now you'll have the desired `cd` selected.
This PR fixes that.
> fix cursor movement across beginning of selection

- keymaps/vim-mode.cson
- spec/prefixes-spec.coffee
this expands #720 with the ability to cancel a `ctrl-r` with `esc` and stay in insert mode.
> cancel insert-mode ctrl-r with escape

- lib/vim-state.coffee
- spec/vim-state-spec.coffee
When working with multiple selections, one may end up with selections with different directions. This PR changes the behaviour of the `o` command to harmonize selection directions. I believe this will be helpful; discussion welcome.
> harmonize selection directions (reversion) on `o`

- lib/operators/input.coffee
- lib/vim-state.coffee
- spec/operators-spec.coffee
On the only line in a file, `cc` should not add a `\n`.
Also, finished the implementation of SubstituteLine with Change (alias `S` to `cc` as it should be).
> Fix cc on only line

- lib/text-objects.coffee
- spec/text-objects-spec.coffee
Fixes #689. Also makes the handling of blank lines, and lines that only contain whitespace more like in vim, e.g. you can now select the lines between two paragraphs by doing 'vip' .
> Fix for #689 and improve blank line handling for the ip/ap text-objects

- docs/operators.md
- lib/operators/indent-operators.coffee
- spec/operators-spec.coffee
Preceding '>' with a number didn't indent lines multiple times, but this fixes that.
> Indent operations preceded by a number should indent multiple times in visual mode.

- lib/motions/general-motions.coffee
- spec/motions-spec.coffee
- spec/operators-spec.coffee
- spec/vim-state-spec.coffee
Fixes #737.
Differs from VIM in that if the visual mode selection was characterwise over multiple lines, and the last line of the selection was longer than the corresponding line where we are redoing the operation, VIM would remove the newline and this PR doesn't. See #737 for more information on this.
Any comments will be welcome.
> fix redoing visual mode operations with `.`

- lib/text-objects.coffee
- spec/text-objects-spec.coffee
This should close issue #759. But I'm not entirely sure this code is the best way to deal with it so feedback is welcome!
> Text Objects in normal mode without a preceding operator should select text.

- lib/motions/search-motion.coffee
- lib/view-models/search-view-model.coffee
- styles/vim-mode.less
When doing a search, display the command '/' or '?' instead of
nothing. This gives the user a visual feedback about what he is
doing.
This is achieved by adding dynamically some classes to the
element container. The CSS class selectors associated display
a content ('/' or '?') before the container.
> Add visual feedback for search command ('/','?')

- lib/operators/input.coffee
- spec/motions-spec.coffee
- spec/operators-spec.coffee
When a motion matches nothing, e.g. `%` on a line without brackets, or `fx` on a line without x, `c` should be cancelled and go into command mode; currently it simply behaves like `i`. 
This PR implements the desired behaviour.
Also, this PR adds a lot of tests for `c%`; I wrote those when I mistakenly thought there was some other problem there so I wanted to document the desired behaviour and fix it, and then I found it already worked as I'd described it. If the tests are undesirable, I can remove them.
> Canceling c operator

- lib/view-models/search-view-model.coffee
- lib/view-models/view-model.coffee
- lib/view-models/vim-normal-mode-input-element.coffee
- spec/operators-spec.coffee
- spec/spec-helper.coffee
- spec/text-objects-spec.coffee
- styles/vim-mode.less
Also removed the seemingly unnecessary editorContainer; this may
affect people’s personal styles if anybody has applied styles to that
container element.
The change in spec-helper makes sure that the new code’s expectations
are met when testing.
This is an alternative solution to PR #776.
> Hide command input field better

- lib/operators/general-operators.coffee
- spec/operators-spec.coffee
- spec/scroll-spec.coffee
Yank currently shows the target of the motion, for example on a line that's longer than the screen, `y$` will scroll so that the end of the line is visible, and `yn` will scroll to the next search match, even if that means that the cursor goes off-screen. This PR fixes that.
I don't know how to spec it, similarly to #558 .
> fix: yank should not scroll

- spec/motions-spec.coffee
- spec/operators-spec.coffee
- spec/spec-helper.coffee
Running specs shouldn’t beep if the beeps are expected. The patch contains commented code that, if uncommented, will print out messages when beep is called and not expected `toHaveBeenCalled()`.
> Suppress beeps in specs

- lib/operators/indent-operators.coffee
- spec/operators-spec.coffee
Indent, e.g. `>>`, should not collapse multiple cursors. This PR fixes it.
Here's steps to reproduce the problem:
1. add a few cursors (e.g. with `cmd-click`)
2. press `>>`, each line gets indented
3. observe that cursors other than the last one are gone
> Fix multi-cursor indent

- styles/vim-mode.less
I've noticed that in the evolution of #777, I forgot to update the style to match the new DOM structure. This fixes that and now the normal mode input element is truly hidden.
> really hide the hidden text editor

- lib/vim-state.coffee
- spec/motions-spec.coffee
- spec/vim-state-spec.coffee
Fixes #806 and #826 and #829.
I don't know how to add specs for the mouse movements but they are fixed too. @maxbrunsfeld please advise if you would like those specs and know how to do them.
> Fix 806 regression

- lib/motions/find-motion.coffee
- lib/motions/general-motions.coffee
- lib/motions/move-to-mark-motion.coffee
- lib/motions/search-motion.coffee
- spec/operators-spec.coffee
This PR addresses one functionality issue with inclusive motion backwards: inclusive movement backwards should include the character under cursor. 
At the moment in vim-mode, only `%` is an inclusive movement that can go backwards, so only it is affected. When search gets postfixes (basically `/e`), or when we implement operator-pending `v` motions (e.g. `dvb` is an inclusive version of `db`), other motions too will be affected.
The PR is seemingly more involved than it would have to be, but IMHO it includes useful cleanups:
1. the `operatesInclusively` flag in `Motion` should be `false` by default because inclusive motions are the exception, the norm is exclusive motions.
2. I removed the `operatesInclusively` flag where it's redundant.
3. I distinguished between non-visual selection for …
> Inclusiveness fixes

- lib/view-models/vim-normal-mode-input-element.coffee
- spec/motions-spec.coffee
- spec/operators-spec.coffee
Fixes #791.
Adapted from [atom/autocomplete-plus](https://github.com/atom/autocomplete-plus/blob/90ae1f3ac5c2a7a46bacf3c1b7c891e1902aad42/lib/autocomplete-manager.coffee#L76)'s workaround for atom/atom#5414.
Specs adapted from atom/atom#8526 .
> ignore input during IME composition in VimNormalModeInputElement

- lib/motions/general-motions.coffee
- lib/operators/general-operators.coffee
- lib/operators/indent-operators.coffee
- lib/operators/input.coffee
- spec/operators-spec.coffee
Fixes #838.
The issue was that some operators (including `=`) had an unnecessary default `count` of 1, but the `G` motion is exceptional in that its default is different from 1. The specs never tested the combination of G with the offending operators, now they do.
> Fix default counts

- README.md
**Proposed changes:**
- The text used to read *"vim-mode has some issues with international keyboard layouts"*. The *"International"* part was too general in my opinion, so I changed it to *"non-US"* which - [in my experience](https://github.com/atom/vim-mode/issues/853) - is true.
- A solution which worked really well for *me* was to install [*keyboard-localization*](https://atom.io/packages/keyboard-localization). I *imagine* more people will find it useful - could be a good idea to mention it.
**Other:**
- When I read *"international"* I thought of countries whose native language isn't English (e.g. France and Turkey). I *definitely* thought UK and US were similar enough but it turns out UK is different enough to cause problems. I imagine that other people in the UK could get confused …
> Made clause about international keyboards specific

- lib/motions/general-motions.coffee
- lib/operators/general-operators.coffee
- lib/scroll.coffee
- package.json
- spec/motions-spec.coffee
- spec/operators-spec.coffee
- spec/scroll-spec.coffee
- spec/spec-helper.coffee
This will probably fail on Travis, as the new version hasn't been released yet. However, specs pass locally :white_check_mark: and the package seems to work just fine.
The changes in this PR are quite straightforward, but I think it's fine if we :ship: this as soon as the new editor version lands. Also, we should probably bump the engine version in `package.json`.
/cc: @maxbrunsfeld for :eyes:
> Fix deprecated methods

- spec/motions-spec.coffee
ctrl-u moves up the screen but the spec description said it moved down.
> :bug: Fix spec description for ctrl-u

- keymaps/vim-mode.cson
- lib/motions/general-motions.coffee
- lib/vim-state.coffee
- spec/motions-spec.coffee
This PR implements the traditional `)` and `(` keybindings originally found in vim. I would greatly appreciate any comments and feedback on how I made it work with regex, as I'm certain there may be a slightly slicker way to pull it off (though I've tried to do similar to how other motions are implemented).
> Implement sentence motions.

- lib/text-objects.coffee
- spec/text-objects-spec.coffee
This fixes the current behavior where `ciw` and related commands cut off delimeters before words when on the first letter.  IE for "/foo/bar/whatever"  would become "/foo/whatever" if you navigated to the 'b' and ran `diw`
As far as I can tell this behavior is caused because `selection.expandOverWord` expands to 2 words when the selection is empty and the cursor is "between" 2 words.  Even though vim-mode uses block cursor, atom considers your cursor to be between the "/" word and the "bar" word.  
I've resolved this by explicitly selecting forward if the selection is empty and then expanding to word.  
This closes #868
> Fix c/d/y iw/aw commands when run from the first character of a word to not include delimeters

- lib/motions/general-motions.coffee
- spec/motions-spec.coffee
- spec/spec-helper.coffee
Fixes https://github.com/atom/vim-mode/issues/903
> Deal with not-yet-rendered scroll position changes in scrolling commands

- lib/motions/general-motions.coffee
- spec/motions-spec.coffee
Depends on https://github.com/atom/atom/pull/9444
> Use model-level scrolling API if available

- keymaps/vim-mode.cson
for vim parity map | (pipe) to move-to-beginning-of-line
> map | (pipe) to move-to-beginning-of-line

- lib/scroll.coffee
- spec/scroll-spec.coffee
> Use model scroll api in scroll commands

- keymaps/vim-mode.cson
Vim mode way navigation in [atom/tree-view](https://github.com/atom/tree-view)
> Navigation for tree-view

- lib/operators/input.coffee
- lib/vim-state.coffee
Hi all,
I took a shot at fixing the repeat-insertions-after-change bug referenced in #1006 and #1010. As @t9md pointed out, there is an issue with `item.confirmChanges(changes)` function of the `Insert` class. That function constructs an instance of `TransactionBundler` which relies on `change.newRange` and some other properties which don't exist. As a result, `bundler.buildInsertText()` always returns `""`, which is why the dot-command after `cwText` repeats the deletion, but not the insertion.
This fix makes use of the `getChangesSinceCheckpoint` function, implemented in atom/text-buffer@9f9025fd7dbac7b1bf2ebc58bf1176df9d9f251c. That function replaces the function of the same name implemented in `lib/vim-state.coffee`, which uses private API's. It essentially supplies equivalent …
> :bug: Fix repeat-insertion bug referenced in #1006

- README.md
On this comment:
https://github.com/atom/vim-mode/issues/1045#issuecomment-250221562
It was recommended that vim-mode-plus be used in place of vim-mode. This PR documents that so new users will know to go there.
> Document that package is deprecated

- package.json
This builds on #1070 and changes the package description to make it clear that vim-mode-plus should be installed instead.  After this is merged a new patch should be released.
We should also consider moving this repository to the atom-archive organization.
/cc @maxbrunsfeld @t9md
> Add deprecation notice to package description
