atom/vim-mode

spec/motions-spec.coffee

the test now seems to work, so it can be uncommented

`0` keybinding fixme seems to be fixed

---

lib/operators/input.coffee

removing attribute that's never used;
fixing a comment that doesn't seem accurate

small cleanups

---

.gitignore
coffeelint.json
lib/motions/find-motion.coffee
lib/motions/general-motions.coffee
lib/motions/search-motion.coffee
lib/operators/general-operators.coffee
lib/operators/index.coffee
lib/operators/input.coffee
lib/operators/put-operator.coffee
lib/panes.coffee
lib/prefixes.coffee
lib/scroll.coffee
lib/status-bar-manager.coffee
lib/text-objects.coffee
lib/utils.coffee
lib/view-models/vim-command-mode-input-element.coffee
lib/vim-mode.coffee
lib/vim-state.coffee
package.json
spec/motions-spec.coffee
spec/operators-spec.coffee
spec/spec-helper.coffee

Refs atom/atom#6230, atom/atom#5982

Add coffeelint support

---

lib/operators/replace-operator.coffee
lib/vim-state.coffee
spec/operators-spec.coffee

I’ve tried to test for this but failed, please advise.
Please note the commit comment for a308480 .
Fixes #549 I think.

Canceling replace

---

docs/operators.md
keymaps/vim-mode.cson
lib/operators/increase-operators.coffee
lib/operators/index.coffee
lib/vim-state.coffee
spec/operators-spec.coffee

ctrl-a and ctrl-x for increasing/decreasing numbers

---

lib/operators/general-operators.coffee
lib/operators/input.coffee

Since I made PR #621, I've learned about `Selection:deleteSelectedText()`, and I only realized now that it applies there. Sorry.

use a better method on Selection

---

lib/operators/input.coffee
lib/vim-state.coffee

:warning: Tests fail against Atom release versions < 0.200 :warning:
This code used private TextBuffer APIs that have changed as of Atom 0.200.0

Update Input repeat handling to work w/ new TextBuffer

---

README.md

I added a link to the ex-mode plugin in the readme, since the two projects are closely related.

added a link to ex-mode in readme

---

keymaps/vim-mode.cson
lib/motions/general-motions.coffee
lib/vim-state.coffee
spec/motions-spec.coffee

Hopefully fixes https://github.com/atom/vim-mode/issues/672
This is my first Atom code, very open to suggestions.

add the g_ motion

---

lib/text-objects.coffee
lib/vim-state.coffee
spec/text-objects-spec.coffee

This should fix #674. I also ended up changing the inner paragraph text-object after I noticed that it didn't work as in vim. Now it seems to behave as in vim, which I am assuming is desirable.

Add the ap text-object, modify the ip text-object,

---

.coffeelintignore
coffeelint.json
lib/motions/find-motion.coffee
lib/motions/move-to-mark-motion.coffee
lib/motions/search-motion.coffee
lib/operators/general-operators.coffee
lib/operators/replace-operator.coffee
lib/vim-mode.coffee
lib/vim-state.coffee
package.json
spec/motions-spec.coffee
spec/operators-spec.coffee
spec/vim-state-spec.coffee

Refs https://github.com/atom/atom/issues/5982

Update coffeelint support

---

lib/operators/increase-operators.coffee
lib/settings.coffee
spec/operators-spec.coffee

add configuration setting for ctrl-a/x number regexps

---

lib/operators/indent-operators.coffee
spec/operators-spec.coffee

Exit visual mode on indent/unindent

---

styles/vim-mode.less

As discussed in https://github.com/atom/vim-mode/pull/777

give operator-pending mode a rectangle cursor

---

README.md

See: https://github.com/atom/vim-mode/issues/796#issuecomment-125340871

Update README: Vim-mode should support soft-wrap

---

lib/operators/input.coffee
spec/operators-spec.coffee

Fix #625. Makes `S` an alias for `cc` and fixes `cc` to do what `S` used to do, when combined with linewise motions.

fix `cc`, make `S` an alias for `cc`

---

lib/status-bar-manager.coffee
lib/vim-mode.coffee

Fixes #567 and #755.
I'm struggling with how to test this, though – guidance welcome. :smiley:

make status bar content follow the current text editor

---

lib/text-objects.coffee
lib/utils.coffee
spec/text-objects-spec.coffee

make text objects expand the selection, not replace it

---

keymaps/vim-mode.cson

This works in vi and vim --- might as well work in vim-mode too.

Activate vim insert mode by pressing 'Insert' key.

---

lib/motions/general-motions.coffee
lib/operators/general-operators.coffee
lib/scroll.coffee
package.json
spec/motions-spec.coffee
spec/operators-spec.coffee
spec/scroll-spec.coffee
spec/spec-helper.coffee

Revert "Fix deprecated methods"

---

lib/motions/general-motions.coffee
lib/operators/general-operators.coffee
lib/scroll.coffee
package.json
spec/motions-spec.coffee
spec/operators-spec.coffee
spec/scroll-spec.coffee
spec/spec-helper.coffee

Fix deprecated methods

---

keymaps/vim-mode.cson

@maxbrunsfeld Removed the commas as we discussed. Sorry for the "blunder".

Remove unneccsary commas in vim-mode.cson

---

lib/settings.coffee

Use clipboard as default register by default

---

package.json
styles/vim-mode.less

Fixes #1079
/cc: @simurai for 👀

Stop using shadow DOM selectors
